name: Test
on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: [flake8, isort, black, readme]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install tox and any other dependencies for test
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Run tox
        run: tox -e ${{ matrix.env }}
